server:
  port: 8300
spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        namespace: 187e40df-495b-4655-ba8f-5c1ab017e88f
        group: DEV_GROUP
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.239.131:3306/gulimall_pms?serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.angel.product.dao: debug